package yowyob.comops.api.tp.adapter.in.web;

import yowyob.comops.api.common.domain.model.PartyType;
import yowyob.comops.api.tp.domain.model.ThirdParty;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.UUID;

public record ThirdPartyResponse(
        UUID id,
        UUID tenantId,
        UUID organizationId,
        PartyType partyType,
        UUID partyId,
        String code,
        boolean enabled,
        String referenceCode,
        String displayName,
        Set<String> roles,
        boolean prospect,
        String accountingAccount,
        String segment,
        Integer qualificationScore,
        Instant lastContactedAt,
        Instant nextFollowUpAt,
        String followUpStatus,
        boolean active,
        Instant convertedAt,
        // canonical fields
        String type,
        String legalForm,
        String uniqueIdentificationNumber,
        String tradeRegistrationNumber,
        String name,
        String acronym,
        String longName,
        String logoUri,
        UUID logoId,
        List<String> accountingAccountNumbers,
        List<String> authorizedPaymentMethods,
        BigDecimal authorizedCreditLimit,
        BigDecimal maxDiscountRate,
        boolean vatSubject,
        BigDecimal operationsBalance,
        BigDecimal openingBalance,
        Integer payTermNumber,
        String payTermType,
        String thirdPartyFamily,
        String classification,
        String taxNumber,
        int loyaltyPoints,
        int loyaltyPointsUsed,
        int loyaltyPointsExpired,
        Instant deletedAt) {

    public static ThirdPartyResponse from(ThirdParty tp) {
        return new ThirdPartyResponse(
                tp.id(),
                tp.tenantId(),
                tp.organizationId(),
                tp.partyRef().partyType(),
                tp.partyRef().partyId(),
                tp.code(),
                tp.enabled(),
                tp.referenceCode(),
                tp.displayName(),
                tp.roles(),
                tp.prospect(),
                tp.accountingAccount(),
                tp.segment(),
                tp.qualificationScore(),
                tp.lastContactedAt(),
                tp.nextFollowUpAt(),
                tp.followUpStatus(),
                tp.active(),
                tp.convertedAt(),
                tp.type(),
                tp.legalForm(),
                tp.uniqueIdentificationNumber(),
                tp.tradeRegistrationNumber(),
                tp.name(),
                tp.acronym(),
                tp.longName(),
                tp.logoUri(),
                tp.logoId(),
                tp.accountingAccountNumbers(),
                tp.authorizedPaymentMethods(),
                tp.authorizedCreditLimit(),
                tp.maxDiscountRate(),
                tp.vatSubject(),
                tp.operationsBalance(),
                tp.openingBalance(),
                tp.payTermNumber(),
                tp.payTermType(),
                tp.thirdPartyFamily(),
                tp.classification(),
                tp.taxNumber(),
                tp.loyaltyPoints(),
                tp.loyaltyPointsUsed(),
                tp.loyaltyPointsExpired(),
                tp.deletedAt());
    }
}
