<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>yowyob.comops.api</groupId>
    <artifactId>RT-Comops</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>RT-comops-bootstrap</artifactId>
  <packaging>jar</packaging>
  <name>iwm-bootstrap</name>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-r2dbc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>r2dbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-pool</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
      <version>2.8.5</version>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-kernel-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-common-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-actor-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-organization-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-tp-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-auth-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-roles-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-administration-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-product-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-inventory-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-resource-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-settings-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-sales-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-accounting-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-treasury-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-file-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>yowyob.comops.api</groupId>
      <artifactId>RT-comops-hrm-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <mainClass>yowyob.comops.api.bootstrap.IwmBackendApplication</mainClass>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
